# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkID=615561

name: 'CTest (BVTs)'

on:
  push:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.nuget/*'
      - build/*.cmd
      - build/*.json
      - build/*.props
      - build/*.ps1
      - build/*.targets
      - build/*.xvd
  pull_request:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.nuget/*'
      - build/*.cmd
      - build/*.json
      - build/*.props
      - build/*.ps1
      - build/*.targets
      - build/*.xvd

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-11-arm
    timeout-minutes: 20

    strategy:
      fail-fast: false

      matrix:
        build_type: [arm64-Release]

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Clone test repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          repository: walbourn/directxtk12test
          path: Tests
          ref: main

      - name: 'Install Ninja'
        run: choco install ninja

      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: arm64

      - name: 'Configure CMake'
        working-directory: ${{ github.workspace }}
        run: cmake --preset=${{ matrix.build_type }} -DBUILD_TESTING=ON -DBUILD_BVT=ON

      - name: 'Build'
        working-directory: ${{ github.workspace }}
        run: cmake --build out\build\${{ matrix.build_type }}

      - name: 'Run BVTs'
        working-directory: ${{ github.workspace }}
        run: ctest --preset=${{ matrix.build_type }} --output-on-failure
